# Site settings
title: Code 4 | What's New
description: "A minimal blog template, built with Jekyll."
url: "https://github.com/codeofour/codeofour.github.io"
author:
  name: "Code 4"
  email: "code0four@gmail.com"
  url: "https://github.com/codeofour/codeofour.github.io"

# Build settings
baseurl: https://codeofour.github.io/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
